name: Publish Gem

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure git
        run: |
          git config user.name "Pyroscope Bot"
          git config user.email "dmitry+bot@pyroscope.io"

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        if: contains(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake build release:source_control_push release:rubygem_push 